[[session]]
name = "ssh connect"
path = "~/"
startup_command = "bash -lc 'if [ -n \"${TMUX:-}\" ]; then tmux rename-session \"ssh-$(date +%d-%H%M%S)\"; fi; exec ssf'"

[[session]]
name = "obsidian note"
path = "~/Obsidian/engineer/0 Inbox/"
startup_command = "onn"

# open the file manager
[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "clear; nvim +'autocmd VimEnter * ++once lua vim.schedule(function() local telescope = require(\"telescope\") pcall(telescope.load_extension, \"file_browser\") telescope.extensions.file_browser.file_browser({ path = vim.loop.cwd(), cwd = vim.loop.cwd(), hidden = true, respect_gitignore = false, grouped = true, initial_mode = \"insert\" }) end)'; clear"

[[session]]
name = "zshrc config"
path = "~/.zshrc"
startup_command = "nvim ~/.zshrc"

[[session]]
name = "neovim config"
path = "~/.config/nvim/lua/"
startup_command = "clear; nvim +'autocmd VimEnter * ++once lua vim.schedule(function() require(\"telescope.builtin\").find_files() end)'; clear"

[[session]]
name = "tmux config"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "hyprland config"
path = "~/.config/hypr/"
startup_command = "nvim hyprland.conf"

# run a script to startup a node project
# [[session]]
# path = "~/c/joshmedeski.com"
# startup_script = "~/.config/sesh/scripts/node_dev"
