[[session]]
name = "terminal-local"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_terminal"

[[session]]
name = "tds-oc"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_tds"

[[session]]
name = "ssh-connect"
path = "~/"
startup_command = "/home/boris/.config/sesh/scripts/start_ssh"

[[session]]
name = "notes-new"
path = "~/Obsidian/engineer/0 Inbox/"
startup_command = "onn"

[[session]]
name = "notes-vault"
path = "~/Obsidian/engineer/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"

# open the file manager
[[session]]
name = "files-downloads"
path = "~/Downloads"
startup_command = "/home/boris/.config/sesh/scripts/nvim_file_browser"

[[session]]
name = "cfg-dotfiles"
path = "~/dotfiles/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"

[[session]]
name = "cfg-zshrc"
path = "~/"
startup_command = "nvim ~/.zshrc"

[[session]]
name = "cfg-nvim"
path = "~/.config/nvim/lua/"
startup_command = "/home/boris/.config/sesh/scripts/nvim_find_files"

[[session]]
name = "cfg-tmux"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "cfg-hypr"
path = "~/.config/hypr/"
startup_command = "nvim hyprland.conf"

[[session]]
name = "cfg-ssh"
path = "~/.ssh/"
startup_command = "nvim config"

[[session]]
name = "cfg-sesh"
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"

# run a script to startup a node project
# [[session]]
# path = "~/c/joshmedeski.com"
# startup_script = "~/.config/sesh/scripts/node_dev"
