# open the file manager
[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "ls"

# open a file
[[session]]
name = "tmux config"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "hyprland config"
path = "~/.config/hypr/"
startup_command = "nvim hyprland.conf"

[[session]]
name = "neovim config"
path = "~/.config/nvim/lua/"
startup_command = "nvim +'autocmd VimEnter * ++once lua vim.schedule(function() require(\"telescope.builtin\").find_files() end)'"

[[session]]
name = "New Obsidian Note"
path = "~/Obsidian/engineer/0 Inbox/"
startup_command = "onn"

# run a script to startup a node project
# [[session]]
# path = "~/c/joshmedeski.com"
# startup_script = "~/.config/sesh/scripts/node_dev"
